<a href="https://colab.research.google.com/github/ZHAOBenyun/Learning-Numpy_Pandas/blob/main/np_fundment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],
          [2,3,4]])

In [3]:
print(array)

[[1 2 3]
 [2 3 4]]


In [8]:
print('number of dim:', array.ndim)

number of dim: 2


In [10]:
print('shape:', array.shape)

shape: (2, 3)


In [11]:
print('size:', array.size)

size: 6


In [18]:
a = np.array([2,3,4], dtype=np.int)  #default int64 since my system is 64 
print(a.dtype)

int64


In [19]:
b = np.array([2,3,4], dtype=np.int32) 
print(b.dtype)

int32


In [20]:
c = np.array([2,3,4], dtype=np.float)  #default float64 since my system is 64 
print(c.dtype)

float64


In [21]:
d = np.array([2,3,4], dtype=np.float16)  #number comes smaller, memory required comes smaller but data comes more inaccurate
print(d.dtype)

float16


In [23]:
zero = np.zeros((3,4))
print(zero.shape)

(3, 4)


In [25]:
one = np.ones((3,4), dtype=np.float32)
print(one.shape)

(3, 4)


In [27]:
empty = np.empty((3,4))
print(empty.shape)

(3, 4)


In [29]:
range = np.arange(10,20,2)  #beginner is included, ender is not
print(range)

[10 12 14 16 18]


In [30]:
reshape1 = np.arange(12).reshape((3,4))
print(reshape1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
linspace = np.linspace(1,12,5)
print(linspace)

[ 1.    3.75  6.5   9.25 12.  ]


In [35]:
reshape2 = np.linspace(1,12,5).reshape((5,1))
print(reshape2)

[[ 1.  ]
 [ 3.75]
 [ 6.5 ]
 [ 9.25]
 [12.  ]]
