<a href="https://colab.research.google.com/github/ZHAOBenyun/Learning-Numpy_Pandas/blob/main/np_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
A = np.arange(3,15)
print(A)
print(A[3])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [4]:
B = np.arange(3,15).reshape((3,4))
print(B)
print(B[2])
print(B[1][3])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
10


In [5]:
for row in B:
  print(row)  #only for row, cannot show column

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [8]:
for column in B.T:
  print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [9]:
print(A.flatten())

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
print(A.flat)

In [11]:
for item in A.flat:
  print(item)

3
4
5
6
7
8
9
10
11
12
13
14
