<a href="https://colab.research.google.com/github/ZHAOBenyun/Learning-Numpy_Pandas/blob/main/np_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([2,3,4,5])
b = np.arange(4)
print("a = ", a)
print("b = ", b)
print(b<3)
print(b==3)

a =  [2 3 4 5]
b =  [0 1 2 3]
[ True  True  True False]
[False False False  True]


In [ ]:
print(b<3)

[ True  True  True False]


In [ ]:
a = a.reshape((2,2))
b = b.reshape((2,2))
print(a)
print(b)

[[2 3]
 [4 5]]
[[0 1]
 [2 3]]


In [ ]:
c = a * b  #Multiply elements by elements
c_dot = np.dot(a,b)  #Multiply elements by elements
c_dot2 = a.dot(b)  #Multiply elements by elements
print(c)
print(c_dot)
print(c_dot2)

[[ 0  3]
 [ 8 15]]
[[ 6 11]
 [10 19]]
[[ 6 11]
 [10 19]]


In [ ]:
A = np.random.random((2,4))
print(A)

[[0.16442558 0.73338884 0.83520875 0.29019208]
 [0.56943248 0.12820776 0.34864519 0.87431994]]


In [ ]:
print(np.sum(A,axis=1))  #axis=1, row, horizontal
print(np.min(A,axis=0))  #axis=0, column, vertical
print(np.max(A))

[2.02321525 1.92060537]
0.12820776391751243
0.8743199396584734


In [ ]:
B = np.arange(2,14).reshape((3,4))
print(B)
print(np.argmin(B))
print(np.argmax(B))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11


In [ ]:
print(np.average(B))

7.5


In [ ]:
print(np.cumsum(B))  #show the cumulatice sum
print(np.diff(B))  #show the difference between each element

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [ ]:
print(np.nonzero(B))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [ ]:
C = np.zeros((3,4))
print(C)
print(np.nonzero(C))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(array([], dtype=int64), array([], dtype=int64))


In [ ]:
B_back = np.arange(14,2,-1).reshape((3,4))
print(B_back)
print(np.sort(B_back))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [ ]:
print(np.transpose(B))
print(B.T)

[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


In [36]:
print(np.clip(B,5,9))  #clip: smaller than 5==5, larger than 9==9

[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [38]:
print(B)
print(np.mean(B, axis=0))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[6. 7. 8. 9.]
