<a href="https://colab.research.google.com/github/ZHAOBenyun/Learning-Numpy_Pandas/blob/main/np_operation2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np

### ***Combination***

In [6]:
A = np.array([1,1,1])

In [7]:
B = np.array([2,2,2])

In [8]:
C = np.vstack((A,B))  #vertical stack
print(C)

[[1 1 1]
 [2 2 2]]


In [11]:
print(A.shape, C.shape)

(3,) (2, 3)


In [9]:
D = np.hstack((A,B))  #horizontal stack
print(D)

[1 1 1 2 2 2]


In [10]:
print(A.shape, D.shape)

(3,) (6,)


In [14]:
######### 
A_new = A[:,np.newaxis]
print(A_new.shape)

(3, 1)


In [15]:
A_new1 = A[np.newaxis,:]
print(A_new1.shape)

(1, 3)


In [18]:
B_new = B[:,np.newaxis]
print(B_new.shape)

(3, 1)


In [19]:
B_new1 = B[np.newaxis,:]
print(B_new1.shape)

(1, 3)


In [24]:
C0 = np.concatenate((A_new,B_new,B_new,A_new), axis=1)
C1 = np.concatenate((A_new,B_new,B_new,A_new), axis=0)
print(C0)
print(C1)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


### ***Segmentation***

In [33]:
A = np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
print(np.split(A,2, axis=1))  #segment into 2 identical block

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [39]:
print(np.split(A,3, axis=0))  #segment into 3 identical block

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [40]:
# print(np.split(A,3, axis=1))  will come error due to not identical block
print(np.array_split(A,3, axis=1))  #segement into 3 different block

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [48]:
print(np.vsplit(A,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [49]:
print(np.hsplit(A,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


### ***Copy***

In [50]:
a = np.arange(4)

In [51]:
b = a  #normal copy
c = a
d = b

In [52]:
a[0] = 11
print(a)

[11  1  2  3]


In [55]:
b is a

True

In [56]:
print(b)

[11  1  2  3]


In [58]:
d[1:3] = [33,22]

In [59]:
d is a

True

In [65]:
print(a)

[11 33 22 44]


In [66]:
e = a.copy() #deep copy
print(e)

[11 33 22 44]


In [67]:
a[3] = 44

In [64]:
print(a)
print(e)

[11 33 22 44]
[11 33 22  3]
